<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>IPCSoftware.Common.CommonExtensions</RootNamespace>
    <AssemblyName>IPCSoftware.CommonExtensions</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\IPCSoftware.Communication.UIClientComm\IPCSoftware.Communication.UIClientComm.csproj" />
  </ItemGroup>
</Project>
